version: "3"

networks:
  stackNetwork:
    name: stack_${APP_ENV:-dev}_network

  stackTraefikNetwork:
    external:
      name: stack_${APP_ENV:-dev}_traefik_network

volumes:
  stackDatabaseVolume:
    name: stack_${APP_ENV:-dev}_database_volume

services:
  stackDatabase:
    image: mysql:8
    container_name: stack_${APP_ENV:-dev}_database
    networks:
      - stackNetwork
    env_file:
      - ../environment/${APP_ENV:-dev}/stack.env
    volumes:
      - stackDatabaseVolume:/var/lib/mysql

  stackTraefik:
    image: traefik:2.3
    container_name: stack_${APP_ENV:-dev}_traefik
    networks:
      - stackNetwork
      - stackTraefikNetwork
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
